### ISSUE TITLE
ERROR : error when start node nitro use config create from "example/create-rollup-eth"

### ISSUE THREAD

**Issue by kmax4ever** [OffchainLabs/arbitrum-orbit-sdk#101]
hi guys, i try to start my nitro node use config created from sdk "example/create-rollup-eth", but when i start nitro node i received error

``nitro_1          | INFO [05-26|15:54:51.730] created jwt file                         filename=/root/.arbitrum/jwtsecret
nitro_1          | INFO [05-26|15:54:51.730] Running Arbitrum nitro node              revision=development vcs.time=development
nitro_1          | INFO [05-26|15:54:52.044] connected to l1 chain                    l1url=https://sepolia-rollup.arbitrum.io/rpc l1chainid=421,614
nitro_1          | INFO [05-26|15:54:52.044] retaining ability to lookup full transaction history as archive mode is enabled 
nitro_1          | ERROR[05-26|15:54:52.273] unable to find validator machine directory for the on-chain WASM module root err="stat /home/user/target/machines/0x8b104a2e80ac6165dc58b9048de12f301d70b02a0ab51396c22b4b4b802a16a4: no such file or directory"` `
what i can do to fix that ?

**Comment by fionnachan** [comment]
Hi @kmax4ever, can you please join https://discord.gg/arbitrum and go to the #noderunning channel? The support team will be able to answer questions regarding node running, thank you!
