### ISSUE TITLE
chainId lookup in createRollupFetchTransactionHash always evaluates to false

### ISSUE THREAD

**Issue by antonio-altr** [OffchainLabs/arbitrum-orbit-sdk#152]
https://github.com/OffchainLabs/arbitrum-orbit-sdk/blob/1e5a32be215968c4e184675c4d8fbc142cdbf33b/src/createRollupFetchTransactionHash.ts#L67

When I ran this code with `publicClient` for Sepolia it seems like it always evaluated to false, and hence `fromBlock` was always set to "earliest"

Using the more verbose way worked for me:
```
  var found = false;
  for (const key in earliestRollupCreatorDeploymentBlockNumber) {
    if (chainId.toString() == key) {
      found = true;
      break;
    }
  }
  const fromBlock = found ? earliestRollupCreatorDeploymentBlockNumber[chainId] : 'earliest';
```

**Note**: I was looking into `createRollupFetchTransactionHash` because the call to `publicClient.getLogs` can fail for many RPC endpoints that limit the number of blocks you can query. This function can be improved to loop on getLogs and avoid the problem.

**Comment by Navasandms** [comment]
Hi

**Comment by spsjvc** [comment]
Fixed in https://github.com/OffchainLabs/arbitrum-orbit-sdk/pull/208 and https://github.com/OffchainLabs/arbitrum-orbit-sdk/pull/213.
