### ISSUE TITLE
Add version of createRollupFetchTransactionHash that limit eth_getLogs block range

### ISSUE THREAD

**Issue by antonio-altr** [OffchainLabs/arbitrum-orbit-sdk#206]
Many RPC providers limit the range of eth_getLogs to something like 10k blocks

**Comment by spsjvc** [comment]
@antonio-altr we're working on this 👍

**Comment by spsjvc** [comment]
Solved in https://github.com/OffchainLabs/arbitrum-orbit-sdk/pull/208.
